name: Docker Build

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          key: docker-${{ hashFiles('requirements.txt') }}
          path: /tmp/.cache

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: myapp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Security scan
        uses: docker/scan-action@v2
        with:
          image: myapp:latest
          exit-code: '1'
